In [1]:
import numpy
print(numpy.version.version)

1.21.4


In [3]:
import numpy as np
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [4]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [5]:
import numpy as np

a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
print(np.arange(4))

[0 1 2 3]


In [11]:
print(np.arange(0,10,2)) # (start, stop, step)

[0 2 4 6 8]


In [12]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
np.delete(arr, 1) #hapus index ke-1

array([1, 3, 4, 5, 6, 7, 8])

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [19]:
array_example.ndim #jumlah axes, atau dimensi dari array.

3

In [20]:
array_example.size # jumlah total elemen array

24

In [21]:
array_example.shape # menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array
                    # Jika, misalnya, kalian memiliki larik 2D dengan 2 baris dan 3 kolom, maka bentuk larik Anda adalah (2,3)

(3, 2, 4)

In [22]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [23]:
arr_one.ndim

2

In [24]:
arr_one.size

5

In [25]:
arr_one.shape

(1, 5)

In [27]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [32]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [33]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [37]:
data = np.array([1,2,3])

In [38]:
print(data)

[1 2 3]


In [39]:
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [40]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [42]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [43]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [44]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [45]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [48]:
a_1 = np.array([[1, 1],
     [2, 2]])

In [49]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [50]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [51]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [53]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [54]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [55]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a = np.array([1, 2, 3, 4])
# Add all of the elements in the array
a.sum()

10

In [60]:
b = np.array([[1, 1], [2, 2]])

# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [62]:
# You can sum the columns

b.sum(axis=1) 

array([2, 4])

In [63]:
data = np.array([1, 2])
data

array([1, 2])

In [64]:
ones = np.ones(2)
ones

array([1., 1.])

In [65]:
data + ones

array([2., 3.])

In [66]:
data * data

array([1, 4])

In [67]:
data/data

array([1., 1.])

In [68]:
data*2

array([2, 4])

In [69]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [70]:
A.sum()

4.8595784

In [71]:
A.min()

0.05093587

In [72]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [73]:
A.max()

0.82485143

In [74]:
A.max(axis=1) # nilai maximum per baris

array([0.5510652 , 0.55645993, 0.82485143])

In [75]:
A.std() #nilai standard deviasi

0.21392120766089617

In [76]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.2729823  0.7760678 ]
 [0.56957306 0.0229516 ]
 [0.97608737 0.9240888 ]]


In [77]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [78]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [79]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [80]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [81]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [82]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [83]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [84]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [85]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [86]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [87]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [88]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [89]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [92]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [93]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [94]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [95]:
print(np.random.random((4,3,2)))

[[[0.23312771 0.26101648]
  [0.86481134 0.80242454]
  [0.18422478 0.55821076]]

 [[0.47508465 0.46909597]
  [0.49082724 0.98898249]
  [0.68883102 0.85311753]]

 [[0.84746974 0.10546206]
  [0.27592475 0.79798057]
  [0.25176589 0.0503268 ]]

 [[0.18873446 0.90511324]
  [0.98747654 0.71246698]
  [0.38710964 0.27842699]]]


In [96]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [97]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined