In [37]:
import numpy as np

mulai = int(input("Mulai: "))
selesai = int(input("Selesai: "))

#Create array 1D
arr = np.arange(mulai,selesai,1) # (start, stop, step)
arr1 = np.array(arr)
print('Array 1D:')
print(arr1)

# Create array 2D
print('Array 2D:')
arr2 = arr1.reshape(3,round(selesai/3))
print(arr2)

# Create array 3D
print('Array 3D:')
arr3 = arr1.reshape(9,round(selesai/9))
print(arr3)


Mulai: 1
Selesai: 28
Array 1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
Array 2D:
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
Array 3D:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]


In [47]:
import numpy as np
import random

n = int(input("Banyak Data: "))
mulai = int(input("Mulai: "))
selesai = int(input("Selesai: "))
data = np.random.randint(mulai,selesai,n)

#Create array 1D
print('Array 1D:')
print(data)

# Create array 2D
print('Array 2D:')
arr2 = data.reshape(4,4)
print(arr2)

# Create array 3D
print('Tukar Posisi:')
tukar = arr2[:, ::-1]
print(tukar)

Banyak Data: 16
Mulai: 1
Selesai: 50
Array 1D:
[24 20 46 35 13 19 19 31 15  4 28 22 36 25 30  6]
Array 2D:
[[24 20 46 35]
 [13 19 19 31]
 [15  4 28 22]
 [36 25 30  6]]
Tukar Posisi:
[[35 46 20 24]
 [31 19 19 13]
 [22 28  4 15]
 [ 6 30 25 36]]


In [49]:
# Array 2D 10x10
x = np.ones((10,10))*4
x[1:-1,1:-1] = 0
print (x)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
